from pydantic import BaseModel, Field
from app.tools.base_tool import BaseTool
from app.tools.context import ToolExecutionContext
from app.llm.factory import get_llm_provider

class RecommendCapaInput(BaseModel):
    detailed_description: str = Field(..., description="The full complaint description.")
    product_name: str = Field(...)
    initial_severity: str = Field(...)

class RecommendCapaOutput(BaseModel):
    recommended_capa: str
    root_cause_hypothesis: str
    message: str

class RecommendCapaTool(BaseTool):
    @property
    def name(self) -> str:
        return "recommend_capa"
        
    @property
    def description(self) -> str:
        return "Generate Corrective and Preventive Action (CAPA) and root cause recommendations based on the complaint."
        
    @property
    def args_schema(self) -> type[BaseModel]:
        return RecommendCapaInput
        
    @property
    def return_schema(self) -> type[BaseModel]:
        return RecommendCapaOutput

    def get_required_fields(self) -> list[str]:
        return ["detailed_description", "product_name", "initial_severity"]
        
    async def execute(self, context: ToolExecutionContext, **kwargs) -> dict:
        llm = get_llm_provider()
        prompt = f"""
        Based on the following Pharmaceutical Complaint for {kwargs['product_name']} with severity {kwargs['initial_severity']}:
        "{kwargs['detailed_description']}"
        
        Generate:
        1. A brief root cause hypothesis.
        2. A recommended Corrective and Preventive Action (CAPA).
        """
        
        try:
            response = await llm.generate_response([{"role": "user", "content": prompt}])
            root_cause = "Generated by AI"
        except Exception:
            root_cause = "Potential packaging, manufacturing, or distribution handling deviation based on complaint details."
            response = (
                "Open a QA investigation, review batch and packaging records, inspect retained samples, "
                "document the confirmed root cause, and implement corrective/preventive actions with effectiveness checks."
            )
        
        return {
            "recommended_capa": response,
            "root_cause_hypothesis": root_cause,
            "message": "CAPA recommendations generated successfully."
        }
