"""Initial schema

Revision ID: 209318d5b937
Revises: 
Create Date: 2026-07-08 20:48:20.246522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209318d5b937'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hcp',
    sa.Column('hcp_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hcp_hcp_code'), 'hcp', ['hcp_code'], unique=True)
    op.create_table('interaction',
    sa.Column('interaction_number', sa.String(length=50), nullable=False),
    sa.Column('hcp_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_date', sa.Date(), nullable=False),
    sa.Column('interaction_type', sa.Enum('EMAIL', 'IN_PERSON', 'VIRTUAL', 'PHONE', name='interactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='interactionstatus'), nullable=False),
    sa.Column('discussion_summary', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_hcp_id'), 'interaction', ['hcp_id'], unique=False)
    op.create_index(op.f('ix_interaction_interaction_date'), 'interaction', ['interaction_date'], unique=False)
    op.create_index(op.f('ix_interaction_interaction_number'), 'interaction', ['interaction_number'], unique=True)
    op.create_index(op.f('ix_interaction_status'), 'interaction', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_status'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_interaction_number'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_interaction_date'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_hcp_id'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_hcp_hcp_code'), table_name='hcp')
    op.drop_table('hcp')
    # ### end Alembic commands ###
