"""Add risk assessment fields

Revision ID: b8b1f3fb1d12
Revises: 209318d5b937
Create Date: 2026-07-27 20:43:53.612619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b1f3fb1d12'
down_revision: Union[str, Sequence[str], None] = '209318d5b937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_customer_code'), 'customer', ['customer_code'], unique=True)
    op.create_table('complaint',
    sa.Column('complaint_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('complaint_source', sa.Enum('EMAIL', 'CALL', 'PDF', 'PORTAL', 'TEXT', name='complaintsource'), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_strength', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_affected', sa.String(length=50), nullable=True),
    sa.Column('complaint_type', sa.String(length=100), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('initial_severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='severity'), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
    sa.Column('status', sa.Enum('PENDING_TRIAGE', 'IN_PROGRESS', 'CLOSED', name='complaintstatus'), nullable=False),
    sa.Column('risk_classification', sa.String(length=100), nullable=True),
    sa.Column('root_cause_recommendation', sa.Text(), nullable=True),
    sa.Column('capa_recommendation', sa.Text(), nullable=True),
    sa.Column('risk_reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_batch_number'), 'complaint', ['batch_number'], unique=False)
    op.create_index(op.f('ix_complaint_complaint_date'), 'complaint', ['complaint_date'], unique=False)
    op.create_index(op.f('ix_complaint_complaint_number'), 'complaint', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_complaint_customer_id'), 'complaint', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaint_status'), 'complaint', ['status'], unique=False)
    op.drop_index(op.f('ix_interaction_hcp_id'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_interaction_date'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_interaction_number'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_status'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_hcp_hcp_code'), table_name='hcp')
    op.drop_table('hcp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hcp',
    sa.Column('hcp_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hospital_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hcp_pkey'))
    )
    op.create_index(op.f('ix_hcp_hcp_code'), 'hcp', ['hcp_code'], unique=True)
    op.create_table('interaction',
    sa.Column('interaction_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hcp_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', postgresql.ENUM('EMAIL', 'IN_PERSON', 'VIRTUAL', 'PHONE', name='interactiontype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='interactionstatus'), autoincrement=False, nullable=False),
    sa.Column('discussion_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('follow_up_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('follow_up_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcp.id'], name=op.f('interaction_hcp_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interaction_pkey'))
    )
    op.create_index(op.f('ix_interaction_status'), 'interaction', ['status'], unique=False)
    op.create_index(op.f('ix_interaction_interaction_number'), 'interaction', ['interaction_number'], unique=True)
    op.create_index(op.f('ix_interaction_interaction_date'), 'interaction', ['interaction_date'], unique=False)
    op.create_index(op.f('ix_interaction_hcp_id'), 'interaction', ['hcp_id'], unique=False)
    op.drop_index(op.f('ix_complaint_status'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_customer_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_complaint_number'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_complaint_date'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_batch_number'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_index(op.f('ix_customer_customer_code'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
